// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectJSON(arg1:string):Promise<string>;

export function ConnectProfile(arg1:string):Promise<string>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DisconnectDB():Promise<void>;

export function ListDatabasesJSON():Promise<string>;

export function ListProfilesJSON():Promise<string>;

export function ListTablesJSON():Promise<string>;

export function LoadTableJSON(arg1:string,arg2:string,arg3:number):Promise<string>;

export function Ping():Promise<string>;

export function SaveProfileJSON(arg1:string,arg2:string):Promise<string>;

export function UpdateCellJSON(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;
