// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectJSON(arg1) {
  return window['go']['main']['App']['ConnectJSON'](arg1);
}

export function ConnectProfile(arg1) {
  return window['go']['main']['App']['ConnectProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DisconnectDB() {
  return window['go']['main']['App']['DisconnectDB']();
}

export function ListDatabasesJSON() {
  return window['go']['main']['App']['ListDatabasesJSON']();
}

export function ListProfilesJSON() {
  return window['go']['main']['App']['ListProfilesJSON']();
}

export function ListTablesJSON() {
  return window['go']['main']['App']['ListTablesJSON']();
}

export function LoadTableJSON(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoadTableJSON'](arg1, arg2, arg3);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function SaveProfileJSON(arg1, arg2) {
  return window['go']['main']['App']['SaveProfileJSON'](arg1, arg2);
}

export function UpdateCellJSON(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateCellJSON'](arg1, arg2, arg3, arg4, arg5, arg6);
}
